services:
  redis:
    image: redis:7.2.5
    container_name: essence-tube-redis
    command: ["redis-server", "--requirepass", "ABC123"]
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis-data:/data
    network_mode: host
