services:
  sqlite:
    image: nouchka/sqlite3
    container_name: logos-auth-sqlite
    volumes:
      - ./.docker/sqlite-data:/root/db
    ports:
      - "9000:9000"
    networks:
      - logos-network

networks:
  logos-network:
